# Agent Config
name: chatgpt
type: vanilla
version: NA
description: Simple GPT-3.5 LLM
prompt_template: !prompt VanillaPrompt
llm:
  model_name: gpt-3.5-turbo
  params:
    temperature: 0.0
    top_p: 0.9
    repetition_penalty: 1.0
    max_tokens: 1000
target_tasks:
  - anything