# general
verbose: True 
private: False

# eval tasks
knowledge:
  world_knowledge: 1
  domain_specific_knowledge: 1
  web_retrieval: 1

reasoning:
  math: 0
  coding: 1
  planning: 0
  commonsense: 0

safety:
  integrity: 0
  harmless: 0

multilingual: 
  translation: 0
  understanding: 0

robustness:
  consistency: 0
  resilience: 0

memory: False



