# general
verbose: True 
private: False

# eval tasks
knowledge:
  world_knowledge: 2
  domain_specific_knowledge: 2
  web_retrieval: 2

reasoning:
  math: 1
  coding: 0
  planning: 0
  commonsense: 1

safety:
  integrity: 1
  harmless: 1

multilingual: 
  translation: 0
  understanding: 0

robustness:
  consistency: 0
  resilience: 0

memory: False



